name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - "v*.*.*"  # Match semantic versioning tags like v1.0.0, v2.3.4, etc.

jobs:
  build:
    runs-on: windows-2022
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      
      - name: Create virtual environment
        run: |
          python -m venv venv
          venv\Scripts\pip install -r requirements.txt

      - name: Build package
        run: |
          venv\Scripts\python build.py
        env:
          PYTHONIOENCODING: utf-8

      - name: Upload release artifacts
        uses: actions/upload-artifact@v4
        with:
          name: FreezeLock
          path: build/main.dist/**  # ✅ 只上传内容，不含 main.dist 目录本身

  release:
    runs-on: ubuntu-24.04
    needs: [build]
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: FreezeLock
      
      - name: Compress release files
        run: zip -r FreezeLock-v${{ github.ref_name }}.zip FreezeLock/

      - name: Create release and upload artifacts
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          release_name: "FreezeLock v${{ github.ref_name }} Release"
          files: FreezeLock-v${{ github.ref_name }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
